<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <AssemblyName>LSPDFRDispatch</AssemblyName>
    <RootNamespace>LSPDFRDispatch</RootNamespace>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="EntryPoint.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="RagePluginHookSDK">
      <HintPath>lib\RagePluginHook.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="LSPD First Response">
      <HintPath>lib\LSPD First Response.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

</Project>
