using System.Collections.Generic;
using Newtonsoft.Json;

namespace LSPDFRDispatch.Models
{
    /// <summary>
    /// A 911 call event generated by the CrimeEventDetector.
    /// Matches the WebSocket message schema: { type: "911_call", data: NineOneOneCall }
    /// </summary>
    public class NineOneOneCall
    {
        [JsonProperty("crime_type")]
        public string CrimeType { get; set; }

        [JsonProperty("location")]
        public CallLocation Location { get; set; }

        [JsonProperty("involved_peds")]
        public List<InvolvedPed> InvolvedPeds { get; set; } = new List<InvolvedPed>();

        [JsonProperty("caller_description")]
        public string CallerDescription { get; set; }
    }

    public class CallLocation
    {
        [JsonProperty("street")]
        public string Street { get; set; }

        [JsonProperty("landmark")]
        public string Landmark { get; set; }

        [JsonProperty("x")]
        public float X { get; set; }

        [JsonProperty("y")]
        public float Y { get; set; }

        [JsonProperty("z")]
        public float Z { get; set; }
    }

    public class InvolvedPed
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }
    }
}
